---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thecodeb/gitinfo.thecodeblog.net/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets-manifest.json $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH